CRA_Project_Tester/CRA_Project_Tester.vcxproj
CRA_Project_Tester/featureTEST.cpp
CRA_Project_Tester/test_run.cpp
CRA_Project_Tester/tester.cpp
CRA_Project_Tester/tester.h

SSDTest run함수 추가 및 Invalid,Invalid Input Test

 테이블 미팅 방향으로 구조 변경점 반영 및 Mock사용하여 Test Case 검증 추가하였습니다.

---

CRA_Project_Tester/test_run.cpp
CRA_Project_Tester/tester.cpp

Test Script 1에 맞게 평가 시나리오 수정

---

CRA_Project_Tester/test_run.cpp
CRA_Project_Tester/tester.cpp
CRA_Project_Tester/tester.h

[[refact]Read시 run을 사용하지 않고 read를 직접 호출하기 때문에, run의 불필요 virtual 제거]
[[feature] FullWrite 함수의 ReadCompare기능 구현하여 read Fail시 Exception 발생]
[[feature]FullWriteAndRead Pass/Fail Case 추가]

Test Case 추가 및 불필요 코드 제거

---

CRA_Project_Tester/test_ara.cpp
CRA_Project_Tester/tester.cpp
CRA_Project_Tester/tester.h

PartialLBAWrite 함수를 구현하여 TDD::Green Code 상태로 변경되었습니다.

[feat] Green, TestScript2 PartialLBAWrite

---

CRA_Project_Tester/test_ara.cpp
CRA_Project_Tester/tester.cpp

RamdomString을 생성하는 함수를 구현하였고, mock test 수행해 pass됨.

[feat] RamdomString 구현 for Tescript3 WriteReadAging

---

CRA_Project_Tester/test_suyong.cpp
CRA_Project_Tester/tester.h

[feature]
1.fullwrite기능구현 및 unit test 검증하였습니다.

[RED/GREEN] FULLWRITE 기능 구현

---

CRA_Project_Tester/tester.h

[feature]main클래스에 testscenario추가 및 위치변경

[feature]main클래스에 testscenario추가 및 위치변경

---

CRA_Project_Tester/CRA_Project_Tester.vcxproj
CRA_Project_Tester/Util.cpp
CRA_Project_Tester/Util.h
CRA_Project_Tester/main.cpp
CRA_Project_Tester/test_run.cpp
CRA_Project_Tester/tester.cpp
CRA_Project_Tester/tester.h

[refact] 기능 함수(createRadomString, CompareBuffer) Util.cpp로 분리

[refact] 기능 함수(createRadomString, CompareBuffer) Util.cpp로 분리

---

CRA_Project_Tester/Util.h
CRA_Project_Tester/tester.cpp

[fix] Util 함수 refactoring과정 중, 함수명 변경 적용 누락

[fix] Util 함수 refactoring과정 중, 함수명 변경 적용 누락

---

CRA_Project_Tester/testScript.cpp
CRA_Project_Tester/testScript.h
CRA_Project_Tester/testShell.h
CRA_Project_Tester/test_ara.cpp

[feat] TDD RED, Testcript4 EraseAndWriteAging
Testcript4 EraseAndWriteAging용 mock test 구현하여, TDD: RED 상태입니다.

[feat] TDD RED, Testcript4 EraseAndWriteAging

---

CRA_Project_Tester/Util.cpp
CRA_Project_Tester/Util.h
CRA_Project_Tester/testScript.cpp
CRA_Project_Tester/testShell.h
CRA_Project_Tester/test_run.cpp

1.FullWriteAndReadCompareTest 구조 변경으로 write값으로data compare하도록 수정
2.Test종료 후 PASS/FAIL cout
3.read시 result값 null처리되는 문제 수정
4. createRandomString Data포맷 수정 : 8자리 + 대문자

[fix] bug fix

---

CRA_Project_Tester/CRA_Project_Tester.vcxproj
CRA_Project_Tester/Logger.cpp
CRA_Project_Tester/Logger.h
CRA_Project_Tester/Util.cpp
CRA_Project_Tester/Util.h
CRA_Project_Tester/test_run.cpp

[feature] Logger class구현 및 기본 Test 추가

[feature] Logger class구현 및 기본 Test 추가

---

CRA_Project_Tester/testRunner.h

Testscript4가 shell에서 호출될 수 있도록 구현하였습니다.

[feat] testRunner.h에 Testsript4 추가

---

CRA_Project_Tester/featureTEST.cpp
CRA_Project_Tester/testRunner.h
CRA_Project_Tester/testShell.h

[feature] erase , erase_range 기능 구현

---

CRA_Project_Tester/testRunner.h
CRA_Project_Tester/testShell.h

[feature] TEST SHELL flush 기능 구현

[feature] TEST SHELL flush 기능 구현

---

CRA_Project_Tester/testShell.h

[fix] LBA 99를 넘어가는 경우 예외 처리

---

CRA_Project_Tester/main.cpp
CRA_Project_Tester/testRunner.h

- as is: shell 수행 후, 파일이름 입력
- to be: shell script.txt와 같이 실행 argument로 파일이름 넘김.

[Fix] Runner 실행 요구사항에 맞게 수정

---

CRA_Project_Tester/CRA_Project_Tester.vcxproj.filters
CRA_Project_Tester/Logger.cpp
CRA_Project_Tester/Logger.h
CRA_Project_Tester/testScript.cpp

[fix]runner의 logger output style 적용을 위한 코드 수정

[fix]runner의 logger output style 적용을 위한 코드 수정

---

CRA_Project_Tester/Logger.cpp
CRA_Project_Tester/testScript.cpp

[hotfix] logger 출력 format 수정
enter두번씩 들어가는 문제 수정

[hotfix] logger 출력 format 수정

---

CRA_Project_Tester/testRunner.h
CRA_Project_Tester/testScript.cpp
CRA_Project_Tester/testScript.h

- TestScript model과 Test Read model & Test Write model간 dependency가 존재. model간 dependency 제거.

[Refactor] Mediator pattern 위반 사항 수정

---

CRA_Project_Tester/CRA_Project_Tester.vcxproj
CRA_Project_Tester/main.cpp
CRA_Project_Tester/testcode_scenario.cpp

1. [Test] Logger Test Coverage 확보
2. cpp 17적용
3. DEBUG/RELEASE 적용

[Test] Logger Test Coverage 확보

---

CRA_Project_Tester/CRA_Project_Tester.vcxproj
CRA_Project_Tester/Logger.cpp
CRA_Project_Tester/Logger.h
CRA_Project_Tester/Util.cpp
CRA_Project_Tester/Util.h
CRA_Project_Tester/testScript.cpp
CRA_Project_Tester/testcode_feature.cpp
CRA_Project_Tester/testcode_scenario.cpp

[refact] Test Scenario Logger관련 Refactoring

[refact] Test Scenario Logger관련 Refactoring

---

CRA_Project_Tester/testRunner.h
CRA_Project_Tester/testScript.cpp

as is: fail 미출력, exception 발생
to be: fail 출력, 정상종료

[Fix] 개별 test script 실행 및 Full test script 실행 중 fail 시, 정상종료하도록 수정.

---

CRA_Project_Tester/testcode_scenario.cpp

[hotfix] testcode_scenario.h 미사용으로 삭제

[hotfix] testcode_scenario.h 미사용으로 삭제

---

CRA_Project_Tester/testShell.h

[refactor] 변수명 변경

---

CRA_Project_Tester/testScript.cpp

- 요구사항: 입력 파일이 존재하지 않는 경우, 에러메시지 출력후 종료
- 미충족: 입력 파일이 존재하지 않는 경우, 에러메시지 출력하지 않고 그냥 종료
- 수정사항: 에러메시지 구문 추가.
* Runner 최종검증 리뷰결과를 첨부하였습니다.

[Fix] Runner 최종 검증 에서 요구사항 미충족 발견하여 수정

---

CRA_Project_Tester/CRA_Project_Tester.vcxproj
CRA_Project_Tester/testcode_scenario.cpp

[Test] Test Coverage확보를 위한 TC 추가

[Test] Test Coverage확보를 위한 TC 추가
